/**
 * Fun facts shown in the in-app footer.
 * One fact is shown per day, determined by the day-of-year index.
 * This means all users see the same fact on the same day.
 */
export const FUN_FACTS: string[] = [
  "The average person will spend over $200,000 on gifts in their lifetime.",
  "Gift wrapping was invented in 1917 by the Hall Brothers (now Hallmark) when they ran out of tissue paper.",
  "The tradition of birthday candles comes from ancient Greece — offerings to Artemis, goddess of the moon.",
  "A study found that experiences make better gifts than material objects for long-term happiness.",
  "In Japan, the wrapping of a gift is considered just as important as the gift itself.",
  "The most popular day for online shopping is Cyber Monday.",
  "Handwritten notes increase the perceived value of a gift by up to 50%.",
  "The word 'gift' comes from the Old Norse word 'gipt', meaning 'good luck'.",
  "Honey never spoils. Archaeologists found 3,000-year-old honey in Egyptian tombs that was still edible.",
  "Octopuses have three hearts and blue blood.",
  "A group of flamingos is called a 'flamboyance'.",
  "The first product to have a barcode was Wrigley's gum.",
  "Bananas are berries, but strawberries aren't.",
  "The shortest war in history lasted 38 to 45 minutes — between Britain and Zanzibar in 1896.",
  "A day on Venus is longer than a year on Venus.",
  "Sloths can hold their breath longer than dolphins — up to 40 minutes.",
  "Scotland's national animal is the unicorn.",
  "The inventor of the Pringles can is buried in one.",
  "Cows have best friends and get stressed when separated.",
  "The first email was sent in 1971 by Ray Tomlinson to himself.",
  "A jiffy is an actual unit of time: 1/100th of a second.",
  "The first oranges weren't orange — they were green.",
  "Wombat poop is cube-shaped.",
  "The average person spends 6 months of their lifetime waiting for red lights.",
  "There are more possible chess games than atoms in the observable universe.",
  "Dolphins sleep with one eye open.",
  "Humans share 60% of their DNA with bananas.",
  "The Eiffel Tower grows about 6 inches in summer due to thermal expansion.",
  "A cloud can weigh over a million pounds.",
  "Bees can be trained to detect explosives.",
  "The longest hiccupping spree lasted 68 years.",
  "Sharks are older than trees.",
  "A group of owls is called a 'parliament'.",
  "Butterflies taste with their feet.",
  "The moon has moonquakes.",
  "There's a basketball court on the top floor of the US Supreme Court building.",
  "Hot water freezes faster than cold water. This is called the Mpemba effect.",
  "A bolt of lightning is five times hotter than the surface of the sun.",
  "Astronauts grow up to 2 inches taller in space.",
  "The average person walks the equivalent of five times around the Earth in their lifetime.",
  "Venus is the only planet that spins clockwise.",
  "Polar bear fur is actually transparent, not white.",
  "The Hawaiian alphabet has only 12 letters.",
  "Peanuts are one of the ingredients in dynamite.",
  "A sneeze travels about 100 miles per hour.",
  "Cats have over 20 vocalizations, including the purr, which heals bones.",
  "Apples float in water because they are 25% air.",
  "The Great Wall of China is not visible from space with the naked eye.",
  "Oxford University is older than the Aztec Empire.",
  "There are more stars in the universe than grains of sand on all Earth's beaches.",
  "An octopus has nine brains — one central and one in each arm.",
  "The shortest complete sentence in English is 'I am' or simply 'Go.'",
  "A single strand of spider silk is thinner than a human hair but five times stronger than steel.",
  "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.",
  "The world's oldest known joke is a Sumerian proverb from 1900 BC.",
  "Honey is the only food that includes all substances necessary to sustain life.",
  "Your nose can remember 50,000 different scents.",
  "The heart of a shrimp is located in its head.",
  "The inventor of the fire hydrant is unknown — the patent was destroyed in a fire.",
  "A photon takes 8 minutes to get from the sun to Earth but 100,000 years to get from the sun's core to its surface.",
  "In Switzerland, it's illegal to own just one guinea pig because they get lonely.",
  "A teaspoon of a neutron star would weigh about 6 billion tons.",
  "Komodo dragons can reproduce without a mate — it's called parthenogenesis.",
  "The total weight of all ants on Earth is roughly equal to the total weight of all humans.",
  "Sea otters hold hands while sleeping so they don't drift apart.",
  "The fingerprints of a koala are so similar to humans that they've confused crime scene investigators.",
  "There's a species of jellyfish that is biologically immortal.",
  "Lobsters were once considered poverty food and fed to prisoners.",
  "The average gift card has a 10-20% chance of never being redeemed.",
  "The tradition of gift registries started in 1924 at a department store in Minneapolis.",
  "Amazon was originally going to be called 'Cadabra' — as in 'abracadabra'.",
  "Ancient Romans exchanged gifts during Saturnalia, the predecessor to Christmas gift-giving.",
  "The most re-gifted item globally is scented candles.",
  "Studies show that spending money on others makes people happier than spending it on themselves.",
  "The concept of a 'wishlist' predates the internet — Sears catalogs had tear-out wish pages in the 1930s.",
  "In South Korea, it's considered rude to open a gift in front of the giver.",
  "The gift-giving industry is worth over $400 billion annually worldwide.",
  "The most popular birthday in the world is September 9th.",
  "Queen Elizabeth II received some unusual gifts: a pair of cowboy boots, a live crocodile, and a box of snail shells.",
  "In the Netherlands, Sinterklaas gifts are accompanied by a personalized poem.",
  "Bubble wrap was originally invented as textured wallpaper.",
  "Your brain uses 20% of your body's total energy despite being only 2% of its mass.",
  "A group of cats is called a 'clowder'.",
  "The average human will eat about 35 tons of food in their lifetime.",
  "Crows can recognize individual human faces and hold grudges.",
  "Glass balls were the original Christmas tree ornaments, invented in Germany.",
  "The world's largest gift was the Statue of Liberty — from France to the US in 1886.",
  "In Greece, gifts are traditionally given on January 1st, not December 25th.",
  "Wrapping paper waste from the holiday season could stretch to the moon and back nine times.",
  "The most expensive gift ever given was the Taj Mahal, built as a gift of love.",
  "Trees can communicate with each other through underground fungal networks.",
  "Elephants are the only animals that can't jump.",
  "The original name for a butterfly was 'flutterby'.",
  "You can hear a blue whale's heartbeat from two miles away.",
  "Sunflowers follow the sun across the sky — it's called heliotropism.",
  "A group of pugs is called a 'grumble'.",
  "The first YouTube video was uploaded on April 23, 2005. It was about elephants at the zoo.",
  "Reading fiction increases your empathy — your brain literally simulates the experiences.",
  "Laughing 100 times is roughly the same workout as 15 minutes on a stationary bike.",
  "The average person will spend about two weeks of their lifetime waiting for traffic lights to change.",
  "Cashews grow on the bottom of cashew apples.",
];

/**
 * Get today's fun fact based on the day of the year.
 * Deterministic — all users see the same fact on the same day.
 */
export function getTodaysFunFact(): string {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return FUN_FACTS[dayOfYear % FUN_FACTS.length];
}