/**
 * Special days mapped by "MM-DD" format.
 * If today matches, this takes priority over the regular fun fact.
 */
export const SPECIAL_DAYS: Record<string, { emoji: string; text: string }> = {
  "01-01": { emoji: "🎆", text: "Happy New Year! A fresh start for wishlists." },
  "01-24": { emoji: "🤗", text: "It's National Compliment Day — tell someone they have great taste." },
  "02-04": { emoji: "🍰", text: "Happy World Cancer Day — kindness heals." },
  "02-09": { emoji: "🍕", text: "It's National Pizza Day. Pizza is always a good gift." },
  "02-14": { emoji: "💝", text: "Happy Valentine's Day! Hope your wishlist is full of love." },
  "02-17": { emoji: "🎲", text: "It's Random Acts of Kindness Day — surprise someone!" },
  "03-01": { emoji: "🤗", text: "World Compliment Day — share one with a friend." },
  "03-08": { emoji: "💐", text: "Happy International Women's Day!" },
  "03-14": { emoji: "🥧", text: "It's Pi Day (3.14). Treat yourself to some pie." },
  "03-17": { emoji: "☘️", text: "Happy St. Patrick's Day! Feeling lucky?" },
  "03-20": { emoji: "😊", text: "It's International Day of Happiness!" },
  "04-01": { emoji: "🃏", text: "April Fools' Day — double-check those wishlists." },
  "04-07": { emoji: "🌍", text: "World Health Day — the best gift is good health." },
  "04-22": { emoji: "🌎", text: "Happy Earth Day! Gift something sustainable." },
  "05-04": { emoji: "⭐", text: "May the Fourth be with you. Star Wars Day!" },
  "05-25": { emoji: "🧹", text: "Towel Day — don't forget your towel." },
  "06-05": { emoji: "🌿", text: "World Environment Day — green gifts matter." },
  "06-08": { emoji: "🌊", text: "World Oceans Day — the ocean is everyone's gift." },
  "06-21": { emoji: "☀️", text: "Summer Solstice — the longest day of the year!" },
  "07-04": { emoji: "🎆", text: "Happy Independence Day to US friends!" },
  "07-17": { emoji: "😂", text: "World Emoji Day — 🎁 is our favorite." },
  "07-30": { emoji: "🤝", text: "International Day of Friendship!" },
  "08-08": { emoji: "🐱", text: "International Cat Day — gift something to your cat." },
  "08-13": { emoji: "🖐️", text: "International Left-Handers Day!" },
  "08-26": { emoji: "🐕", text: "National Dog Day — don't forget the good boys." },
  "09-13": { emoji: "🍫", text: "International Chocolate Day. Enough said." },
  "09-21": { emoji: "☮️", text: "International Day of Peace." },
  "10-01": { emoji: "☕", text: "International Coffee Day — brew something nice." },
  "10-04": { emoji: "🐾", text: "World Animal Day — animals deserve gifts too." },
  "10-10": { emoji: "🧠", text: "World Mental Health Day — take care of yourself." },
  "10-31": { emoji: "🎃", text: "Happy Halloween! Trick or treat... or wishlist?" },
  "11-13": { emoji: "🥰", text: "World Kindness Day — be generous today." },
  "11-19": { emoji: "🧔", text: "International Men's Day!" },
  "11-21": { emoji: "📺", text: "World Television Day — binge-watch guilt-free." },
  "12-05": { emoji: "🤝", text: "International Volunteer Day — give your time." },
  "12-21": { emoji: "❄️", text: "Winter Solstice — the shortest day. Cozy up!" },
  "12-24": { emoji: "🎄", text: "Christmas Eve — the anticipation is the best part." },
  "12-25": { emoji: "🎅", text: "Merry Christmas! Hope your wishlist came true." },
  "12-31": { emoji: "🥂", text: "New Year's Eve — cheers to a year of great gifts!" },
};